[application]
name = "ipa2tipa"
default_platform = "web"

[web.app]
title = "IPA to TIPA"
base_path = ""

[web.watcher]
reload_html = true
watch_path = ["src", "Cargo.toml"]

[web.resource]
style = ["https://fonts.googleapis.com/css2?family=Gentium+Book+Plus:ital,wght@0,400;0,700;1,400;1,700&display=swap"]
script = []

[web.resource.dev]
style = ["https://fonts.googleapis.com/css2?family=Gentium+Book+Plus:ital,wght@0,400;0,700;1,400;1,700&display=swap"]
script = []
